export const ALERT = 'ALERT';
export const AUTH = 'AUTH';
export const USER = {
    GET_USER: 'GET_USER',
    GET_USERS: 'GET_USERS',
    ADD_USER: 'ADD_USER',
    EDIT_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
};

export const MODEL = {
    GET_MODEL: 'GET_MODEL',
    GET_MODELS: 'GET_MODEL',
    ADD_MODEL: 'ADD_MODEL',
};

export const LOT = {
    GET_LOT: 'GET_LOTS',
    PROCEDURE_LOT: 'PROCEDURE_LOT',
    DELIVERY_LOT: 'DELIVERY_LOT',
    RECEIVE_LOT: 'RECEIVE_LOT',
};

export const PRODUCT = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_SELLED_PRODUCT: 'GET_SELLED_PRODUCTS',
    SELL_PRODUCT: 'SELL_PRODUCT',
    DELIVERY_PRODUCT: 'DELIVERY_PRODUCT',
    RECEIVE_PRODUCT: 'RECEIVE_PRODUCT',
    RETURN_CUSTOMER: 'RETURN_CUSTOMER',
};

export const DELIVERY = {
    INCOMING: 'INCOMING',
    DELIVERING: 'DELIVERING',
};

export const STORAGE = {
    GET_STORAGES: 'GET_STORAGES',
};

export const CUSTOMER = {
    GET_CUSTOMERS: 'GET_CUSTOMERS',
    CREATE_CUSTOMER: 'CREATE_CUSTOMER',
};
